name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.bosch.cloud
          username: ${{ secrets.MIRANTIS_BOSCH_CLOUD }}
          password: ${{ secrets.MIRANTIS_ACCESS_TOKEN }}
